In [1]:
# Import Libraries and Connect to AWS S3
import pandas as pd
pd.set_option('display.max_columns', None)
import s3fs
fs = s3fs.S3FileSystem(anon=True)

In [2]:
# List the top-level directories of the MIT Supercloud dataset
print(*fs.ls('s3://mit-supercloud-dataset/'), sep='\n')

mit-supercloud-dataset/2022-hpca
mit-supercloud-dataset/challenges
mit-supercloud-dataset/datacenter-challenge

In [3]:
# List the directories within the datacenter challenge directory
print(*fs.ls('s3://mit-supercloud-dataset/datacenter-challenge/'), sep='\n')

mit-supercloud-dataset/datacenter-challenge/202201

In [4]:
# List the directories within the 202201 directory
print(*fs.ls('s3://mit-supercloud-dataset/datacenter-challenge/202201/'), sep='\n')

mit-supercloud-dataset/datacenter-challenge/202201/LICENSE
mit-supercloud-dataset/datacenter-challenge/202201/README.md
mit-supercloud-dataset/datacenter-challenge/202201/cpu
mit-supercloud-dataset/datacenter-challenge/202201/gpu
mit-supercloud-dataset/datacenter-challenge/202201/labelled_job_stats.csv
mit-supercloud-dataset/datacenter-challenge/202201/labelled_jobids.csv
mit-supercloud-dataset/datacenter-challenge/202201/node-data.csv
mit-supercloud-dataset/datacenter-challenge/202201/slurm-log.csv
mit-supercloud-dataset/datacenter-challenge/202201/tres-mapping.txt

In [19]:
# Read and print the License
content = fs.cat('s3://mit-supercloud-dataset/datacenter-challenge/202201/LICENSE')
print(content.decode('utf-8'))

This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

In [33]:
# Read and print the README
content = fs.cat('s3://mit-supercloud-dataset/datacenter-challenge/202201/README.md')
print(content.decode('utf-8'))

# MIT Supercloud Dataset
This dataset consists of the labelled parts of the data described in the paper [_The MIT Supercloud Dataset_](http://arxiv.org/abs/2108.02037). The archive contains compressed CSV files consisting of monitoring data from the MIT Supercloud system. For details on the capabilites offered by MIT Supercloud cluster see [_Reuther, et. al. IEEE HPEC 2018_](https://arxiv.org/abs/1807.07814).

# Citation
If you use this data in your work, please cite the following paper

```
@INPROCEEDINGS{supercloud,
  author={Samsi, Siddharth and Weiss, Matthew L and Bestor, David and Li, Baolin and Jones, Michael and Reuther, Albert and Edelman, Daniel and Arcand, William and Byun, Chansup and Holodnack, John and Hubbell, Matthew and Kepner, Jeremy and Klein, Anna and McDonald, Joseph and Michaleas, Adam and Michaleas, Peter and Milechin, Lauren and Mullen, Julia and Yee, Charles and Price, Benjamin and Prout, Andrew and Rosa, Antonio and Vanterpool, Allan and McEvoy, Lindsey and Cheng, Anson and Tiwari, Devesh and Gadepally, Vijay},
  booktitle={2021 IEEE High Performance Extreme Computing Conference (HPEC)},
  title={The MIT Supercloud Dataset},
  year={2021},
  volume={},
  number={},
  pages={1-8},
  doi={10.1109/HPEC49654.2021.9622850}
}
```

Please see our website for additional information : https://dcc.mit.edu

Any questions about the dataset can be sent to mit-dcc@mit.edu

# Data Organization
The MIT Supercloud Dataset consists of anonymized scheduler logs, time series data from CPUs and GPUs, monitoring data from each compute node. The uncompressed dataset is of the order of a Terabyte and is made available in compressed files. The dataset includes traces from 460,497 jobs, out of which 98,177 are jobs that requested GPUs for a variety of compute workloads which include AI/ML training and inference. The data is organized in the following directories:

_Note:_ Slurm jobids, compute node hostnames, user ids and other identifiable entries have been anonymized prior to publication of this dataset. Please see the paper above for details.

### CPU utilization
The `cpu` folder contains time-series profiling data collected using the Slurm profiler plugin on each node assigned to a job included in this dataset. The data is organized in 100 subfolders. Each CSV file in the archive contains CPU usage, memory usage and file read/write data collected at 10 second intervals. Also included is a summary of the usage data for each job in the corresponding folder.

### GPU utilization
The GPU utilization data is organized in 100 directories in the `gpu` folder. Each CSV file in these folders contains GPU usage data collected on all GPUs across all nodes assigned to a job. GPU data is collected using the `nvidia-smi` utility at 100 ms intervals.

### Compute node utilization
We include monitoring data collected from each compute node at 5 minute intervals. This includes system load, number of users, number of processes per user, memory usage on the node and total number of Lustre remote procedure calls. This data is contained in the csv file `node-data.csv`. The data in this file provides a snapshot of the node utilization and is independent of the utilization data collected using Slurm.

### Slurm scheduler data
We also include the following data from the Slurm scheduler:

- **slurm-log.csv**: Slurm accounting information for the jobs included in this dataset.

- **tres-mapping.txt**: This file contains a mapping between trackable resources (tres) in Slurm requested by a job. These resources are listed in the `tres_req` column in the `labelled-slurm-log.csv` file. This CSV file maps the integer values to the corresponding resource (e.g.: GPU type, CPU, memory) as shown below:

| Tres ID   |      Resource      |   | Tres ID   |      Resource      |
|:----------:|:-------------:| --------- |:----------:|:-------------:|
| 1 | cpu |     | 6 | fs |
| 2 | mem |     | 7 | vmem |
| 3 | energy |     | 8 | pages |
| 4 | node |     | 1001 | gpu:tesla |
| 5 | billing |     | 1002 | gpu:volta |

### Labeled DNN workloads
This dataset includes 3,425 known deep learning workloads. We provide a mapping between Slurm jobids and the actual model that was trained as part of the job. This relase includes compute workloads from a variety of published, open soure deep neural networks, trained on publicly available data. We provide the following additional files to help identify these jobs in the anonnymized Slurm logs and the corresponding time-series data:

- **labelled_jobids.csv**: This file contains the mapping between Slurm Job IDs and the type of neural network model trained in a given job. Jobs in this dataset consist of standard convolutional neural networks (ResNet, Inception, VGG), U-Nets, Natural Language models and Graph Neural Networks. We include a mix of Tensorflow and pytorch implementations of these models. Current distribution of jobs is listed in the table below:

| Vision Networks   | Job Count || Language Models   | Job Count  || Graph Neural Networks   |  Job Count      |
|----------|:-------------:|-|----------|:-------------:|-|----------|:-------------:|
| VGG | 560 | | Bert | 189 || DimeNet | 33 |
| ResNet | 464 | | DistillBert | 172 || SchNet | 39 |
| Inception | 484 | |||| PNA | 27 |
| U-Net | 1431 | |||| NNConv | 32 |

Data collection of the above jobs is ongoing and this labelled dataset will be further augmented with other types of machine learning and AI workloads over time.

#### Code availability
The known workloads above used open source implementations and publicly available datasets as listed below:

- TensorFlow implementations of VGG, ResNet and Inception are available from https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks
These models were trained on the ImageNet dataset.

- U-Net models used here are described in the paper [_SEVIR : A Storm Event Imagery Dataset for Deep Learning Applications in Radar and Satellite Meteorology_](https://proceedings.neurips.cc/paper/2020/hash/fa78a16157fed00d7a80515818432169-Abstract.html), NeurIPS 2020. Implementations and dataset used for training are available from https://github.com/MIT-AI-Accelerator/neurips-2020-sevir.

- Pytorch implementations of Bert and DistillBert from the HuggingFace library were trained on fine tuning tasks. Available at https://huggingface.co.

- Pytorch implementations of DimeNet, SchNet, NNConv, and PNA are available in the `pytorch-geometric` package. For documentation see the following pages:
  - https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/dimenet.html
  - https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/schnet.html
  - https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.NNConv
  - https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/conv/pna_conv.html

  These models were trained on the QM9 and ZINC datasets.

#### Acknowledgement
Research was sponsored by the United States Air Force Research Laboratory and the United States Air Force Artificial Intelligence Accelerator and was accomplished under Cooperative Agreement Number FA8750-19-2-1000. The views and conclusions contained in this document are those of the authors and should not be interpreted as representing the official policies, either expressed or implied, of the United States Air Force or the U.S. Government. The U.S. Government is authorized to reproduce and distribute reprints for Government purposes notwithstanding any copyright notation herein.

In [5]:
# List first 3 subfolders of cpu directory
print(*fs.ls('s3://mit-supercloud-dataset/datacenter-challenge/202201/cpu')[:3], sep='\n')

mit-supercloud-dataset/datacenter-challenge/202201/cpu/0000
mit-supercloud-dataset/datacenter-challenge/202201/cpu/0001
mit-supercloud-dataset/datacenter-challenge/202201/cpu/0002

In [6]:
# List first 3 files in the cpu 0000 subfolder
print(*fs.ls('s3://mit-supercloud-dataset/datacenter-challenge/202201/cpu/0000')[:3], sep='\n')

mit-supercloud-dataset/datacenter-challenge/202201/cpu/0000/10066852034034-summary.csv
mit-supercloud-dataset/datacenter-challenge/202201/cpu/0000/10066852034034-timeseries.csv
mit-supercloud-dataset/datacenter-challenge/202201/cpu/0000/10094163161543-summary.csv

In [29]:
# View the first CPU summary file (all rows)
df = pd.read_csv('s3://mit-supercloud-dataset/datacenter-challenge/202201/cpu/0000/10066852034034-summary.csv')
df

,Step,Node,Series,ElapsedTime,Min_EpochTime,Max_EpochTime,Sum_EpochTime,Avg_EpochTime,Min_CPUFrequency,Max_CPUFrequency,Sum_CPUFrequency,Avg_CPUFrequency,Min_CPUTime,Max_CPUTime,Sum_CPUTime,Avg_CPUTime,Min_CPUUtilization,Max_CPUUtilization,Sum_CPUUtilization,Avg_CPUUtilization,Min_RSS,Max_RSS,Sum_RSS,Avg_RSS,Min_VMSize,Max_VMSize,Sum_VMSize,Avg_VMSize,Min_Pages,Max_Pages,Sum_Pages,Avg_Pages,Min_ReadMB,Max_ReadMB,Sum_ReadMB,Avg_ReadMB,Min_WriteMB,Max_WriteMB,Sum_WriteMB,Avg_WriteMB
0,-1,r4858666-n911952,0,111710,1611618179,1611729889,18005622307848,1.611674e+09,3403,3403,38018316,3403.000000,0.0,0.00,0.00,0.000000,0.0,0.0,0.0,0.000000,832,2184,9296456,8.321210e+02,7776,168384,87034080,7.790376e+03,0,0,0,0.000000,0.0,0.001858,0.001858,0.000000,0.0,0.002243,0.002243,0.000000
1,batch,r4858666-n911952,0,111710,1611618179,1611729889,18005622307848,1.611674e+09,0,2989,336196,30.092732,0.0,319.84,160195.85,14.339049,0.0,3198.4,1601958.5,143.390485,4980,62724624,359392988936,3.216908e+07,199036,73137884,469415286548,4.201712e+07,0,2,2,0.000179,0.0,46.823552,151.210783,0.013535,0.0,4.239426,35.253897,0.003156

In [31]:
# View the first CPU Time Series file (first 5 rows)
df = pd.read_csv('s3://mit-supercloud-dataset/datacenter-challenge/202201/cpu/0000/10066852034034-timeseries.csv')
df.head(5)

,Step,Node,Series,ElapsedTime,EpochTime,CPUFrequency,CPUTime,CPUUtilization,RSS,VMSize,Pages,ReadMB,WriteMB
0,-1,r4858666-n911952,0,0,1611618179,3403,0.0,0.0,2184,168384,0,0.000000,0.000000
1,-1,r4858666-n911952,0,10,1611618189,3403,0.0,0.0,832,7776,0,0.001858,0.002243
2,-1,r4858666-n911952,0,20,1611618199,3403,0.0,0.0,832,7776,0,0.000000,0.000000
3,-1,r4858666-n911952,0,30,1611618209,3403,0.0,0.0,832,7776,0,0.000000,0.000000
4,-1,r4858666-n911952,0,40,1611618219,3403,0.0,0.0,832,7776,0,0.000000,0.000000

In [7]:
# List first 3 subfolders of gpu directory
print(*fs.ls('s3://mit-supercloud-dataset/datacenter-challenge/202201/gpu')[:3], sep='\n')

mit-supercloud-dataset/datacenter-challenge/202201/gpu/0000
mit-supercloud-dataset/datacenter-challenge/202201/gpu/0001
mit-supercloud-dataset/datacenter-challenge/202201/gpu/0002

In [8]:
# List first 3 files in the gpu 0000 subfolder
print(*fs.ls('s3://mit-supercloud-dataset/datacenter-challenge/202201/gpu/0000')[:3], sep='\n')

mit-supercloud-dataset/datacenter-challenge/202201/gpu/0000/10028747453883-r9175025-n976057.csv
mit-supercloud-dataset/datacenter-challenge/202201/gpu/0000/10047800340911-r4858666-n830961.csv
mit-supercloud-dataset/datacenter-challenge/202201/gpu/0000/10173488764004-r5189505-n911952.csv

In [32]:
# View the first GPU Time Series file (first 5 rows)
df = pd.read_csv('s3://mit-supercloud-dataset/datacenter-challenge/202201/gpu/0000/10028747453883-r9175025-n976057.csv')
df.head(5)

,timestamp,gpu_index,utilization_gpu_pct,utilization_memory_pct,memory_free_MiB,memory_used_MiB,temperature_gpu,temperature_memory,power_draw_W,pcie_link_width_current
0,1.618081e+09,0,0,0,32510,0,34,34,26.10,16
1,1.618081e+09,0,0,0,32510,0,34,34,26.01,16
2,1.618081e+09,0,0,0,32510,0,34,34,26.01,16
3,1.618081e+09,0,0,0,32510,0,34,34,26.01,16
4,1.618081e+09,0,0,0,32510,0,34,34,26.10,16

In [23]:
# View the "labelled_job_stats" table
df = pd.read_csv('s3://mit-supercloud-dataset/datacenter-challenge/202201/labelled_job_stats.csv')
df

                      model  count
0                    U3-128    165
1                     U3-32    165
2                     U3-64    159
3                    U4-128    157
4                     U4-32    163
5                     U4-64    158
6                    U5-128    148
7                     U5-32    158
8                     U5-64    158
9         bert-base-uncased    189
10                     conv     32
11                  dimenet     33
12  distilbert-base-uncased    172
13               inception3    241
14               inception4    243
15                      pna     27
16                resnet101     77
17             resnet101_v2     54
18                resnet152     76
19             resnet152_v2     54
20                 resnet50    111
21            resnet50_v1.5     91
22                   schnet     39
23                    vgg11    185
24                    vgg16    176
25                    vgg19    199

In [24]:
# View the first 3 rows of the "labelled_jobids" table
df = pd.read_csv('s3://mit-supercloud-dataset/datacenter-challenge/202201/labelled_jobids.csv')
df.head(3)

           id_job    model
0  25664193915111  dimenet
1  42371679622969   schnet
2  64971010680493     conv

In [18]:
# View the first 3 rows of the "Node Data" table
df = pd.read_csv('s3://mit-supercloud-dataset/datacenter-challenge/202201/node-data.csv')
df.head(3)

,Node,Time,UserPIDCount,FSlatency,LoadAvg,MemoryFreeInactiveKB,LustreRPCTotals
0,r7217787-n911952,1.614557e+09,91472915699408:11|1706828023724:15|65855960046...,0.0,29.24,371.0,26359.0
1,r4858666-n911952,1.614557e+09,66720169194922:40|,0.0,4.07,363.0,228.0
2,r2582019-n911952,1.614557e+09,22654259079669:47|,0.0,40.01,377.0,2006.0

In [28]:
# View the first 3 rows of the "Slurm Log" table
df = pd.read_csv('s3://mit-supercloud-dataset/datacenter-challenge/202201/slurm-log.csv')
df['time_submit_readable'] = pd.to_datetime(df['time_submit'], unit='s')
df.head(3)

,id_job,id_array_job,id_array_task,id_user,kill_requid,nodes_alloc,nodelist,cpus_req,derived_ec,exit_code,gres_used,array_max_tasks,array_task_pending,constraints,flags,mem_req,partition,priority,state,timelimit,time_submit,time_eligible,time_start,time_end,time_suspended,track_steps,tres_alloc,tres_req,job_type,time_submit_readable
0,82691694838059,38873353215144,2504,42770088536256,61026541062099,1,['r9189566-n911952'],20,0,0,NaN,0,0,xeon-g6,4,9223372036854784308,normal,10237,3,4294967295,1609535703,1609535704,1609806297,1609806605,0,0,"1=20,2=170000,4=1,5=20","1=20,2=170000,4=1,5=20",OTHER,2021-01-01 21:15:03
1,3434806870797,38873353215144,2523,42770088536256,61026541062099,1,['r9189566-n911952'],20,0,0,NaN,0,0,xeon-g6,4,9223372036854784308,normal,10237,3,4294967295,1609535703,1609535704,1609806607,1609807004,0,0,"1=20,2=170000,4=1,5=20","1=20,2=170000,4=1,5=20",OTHER,2021-01-01 21:15:03
2,8370846758272,38873353215144,2543,42770088536256,61026541062099,1,['r9189566-n911952'],20,0,0,NaN,0,0,xeon-g6,4,9223372036854784308,normal,10237,3,4294967295,1609535703,1609535704,1609807004,1609807331,0,0,"1=20,2=170000,4=1,5=20","1=20,2=170000,4=1,5=20",OTHER,2021-01-01 21:15:03

In [30]:
# View the contents of the "tres-mapping.txt" file
path = 's3://mit-supercloud-dataset/datacenter-challenge/202201/tres-mapping.txt'
print(fs.cat(path).decode('utf-8'))

tres_id,resource_type
1,cpu
2,mem
3,energy
4,node
5,billing
6,fs
7,vmem
8,pages
1001,gpu:tesla
1002,gpu:volta